"""Добавка поля buyer_id in Order

Revision ID: 334d591d362b
Revises: a47b764313ad
Create Date: 2025-11-13 21:59:51.757948

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '334d591d362b'
down_revision: Union[str, Sequence[str], None] = 'a47b764313ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('buyer_id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'buyer_id')
    # ### end Alembic commands ###
