"""Делаем поле user_id в модели profiles обязательным

Revision ID: acd70892b4b0
Revises: b8853deb520d
Create Date: 2025-11-13 21:27:24.781879

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'acd70892b4b0'
down_revision: Union[str, Sequence[str], None] = 'b8853deb520d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
