"""Добавление поля bio в модель profiles

Revision ID: b8853deb520d
Revises: d9bec459cdf9
Create Date: 2025-11-13 21:22:54.278008

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8853deb520d'
down_revision: Union[str, Sequence[str], None] = 'd9bec459cdf9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('bio', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profiles', 'bio')
    # ### end Alembic commands ###
