"""Create Search Vector

Revision ID: d9e8d2e24815
Revises: 334d591d362b
Create Date: 2025-11-25 21:45:33.307670

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd9e8d2e24815'
down_revision: Union[str, Sequence[str], None] = '334d591d362b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('tsv', postgresql.TSVECTOR(), sa.Computed("\n            setweight(to_tsvector('english', coalesce(name, '')), 'A')\n            ||\n            setweight(to_tsvector('russian', coalesce(name, '')), 'A')\n            ||\n            setweight(to_tsvector('english', coalesce(description, '')), 'B')\n            ||\n            setweight(to_tsvector('russian', coalesce(description, '')), 'B')\n            ", persisted=True), nullable=False))
    op.create_index('ix_products_tsv_gin', 'products', ['tsv'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_products_tsv_gin', table_name='products', postgresql_using='gin')
    op.drop_column('products', 'tsv')
    # ### end Alembic commands ###
