
TOKEN_URL = 'users/token'
ACCESS_TOKEN_EXPIRE_MINUTES = 30
REFRESH_TOKEN_EXPIRE_DAYS = 7
NAME_TOKEN_HEAD = 'Bearer'

CATEGORY_NAME_MIN_LENGTCH = 3
CATEGORY_NAME_MAX_LENGTCH = 50

PRODUCT_NAME_MIN_LENGTCH = 3
PRODUCT_NAME_MAX_LENGTCH = 100
PRODUCT_DESCRIPTION_MAX_LENGTCH = 500
PRODUCT_MIN_PRICE = 0
PRODUCT_MAX_LENGTH_IMAGE_URL = 200
PRODUCT_MIN_STOCK = 0

USER_NAME_ROLE_BUYER = 'buyer'
USER_NAME_ROLE_SELLER = 'seller'
USER_NAME_ROLE_ADMIN = 'admin'
USER_PASSWORD_MIN_LENGTH = 8

REVIEW_COMMENT_MAX_LENGTH = 500
REVIEW_GRADE_MIN_VALUE = 1
REVIEW_GRADE_MAX_VALUE = 5
