
# TOKEN_URL = 'users/token'
# ACCESS_TOKEN_EXPIRE_MINUTES = 30
# REFRESH_TOKEN_EXPIRE_DAYS = 7
# NAME_TOKEN_HEAD = 'Bearer'

CATEGORY_NAME_MIN_LENGTCH = 3
CATEGORY_NAME_MAX_LENGTCH = 50

PRODUCT_NAME_MIN_LENGTCH = 3
PRODUCT_NAME_MAX_LENGTCH = 100
PRODUCT_DESCRIPTION_MAX_LENGTCH = 500
PRODUCT_MIN_PRICE = 0
PRODUCT_MAX_LENGTH_IMAGE_URL = 200
PRODUCT_MIN_STOCK = 0

PRODUCT_ROUTER_MIN_PAGE = 0
PRODUCT_ROUTER_MIN_SIZE = 1
PRODUCT_ROUTER_MAX_SIZE = 100
PRODUCT_ROUTER_DEFAULT_SIZE = 5

PRODUCT_MIN_RAITENG = 0
PRODUCT_FILTER_MAX_RAITENG = 5
PRODUCT_FILTER_MIN_VALUE_ID_SELLER = 1

USER_NAME_ROLE_BUYER = 'buyer'
USER_NAME_ROLE_SELLER = 'seller'
USER_NAME_ROLE_ADMIN = 'admin'
USER_PASSWORD_MIN_LENGTH = 8

REVIEW_COMMENT_MAX_LENGTH = 500
REVIEW_GRADE_MIN_VALUE = 1
REVIEW_GRADE_MAX_VALUE = 5

TOKEN_DICT_KEY_EMAIL = 'sub'
TOKEN_DICT_KEY_ROLE = 'role'
TOKEN_DICT_KEY_ID = 'id'
